spring:
  kafka:
    bootstrap-servers: 192.168.2.112:9092,192.168.2.113:9092,192.168.2.114:9092
    producer:
          acks: 1
          batch-size: 16384
          buffer-memory: 33554432
          client-id: spring-boot-demo-mq-kafka
          retries: 0
          properties:


    consumer:
      group-id: spring-boot-demo
      enable-auto-commit: false
      auto-offset-reset: latest
      properties:
        session.timeout.ms: 60000
    listener:
      log-container-config: false
      concurrency: 5

      ack-mode: manual_immediate