

spring:
  application:
    name: demo-hello-world
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pJp&Zzk3213
    url: jdbc:mysql://192.168.2.117:3306/mybatis-demo?characterEncoding=utf8&useSSL=true&serverTimezone=UTC&zeroDateTimeBehavior=CONVERT_TO_NULL

