server:
  port: 8002
spring:
  application:
     name: user-provider #不要使用下划线
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/ #告诉服务提供者要把服务注册到哪儿
  instance:
      prefer-ip-address: true #显示客户端真实ip