server:
  port: 7001


spring:
  application:
    name: zuul-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.12.72:3306/enceladus?characterEncoding=UTF-8
    username: root
    password: C!Fr0ShoW9Nu
  redis:
    host: 10.0.12.74
    timeout: 10000ms
    jedis:
      pool:
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
        max-active: 8

mybatis:
  type-aliases-package: com.pd.zuul.auth.model
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
      prefer-ip-address: true #显示客户端真实ip

#路由可以不配置，默认使用服务名称即可请求服务的api
#如下配置将使用path指定的路径请求服务api，可以隐藏服务名称


