server:
  port: 7001

spring:
  application:
    name: zuul-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
      prefer-ip-address: true #显示客户端真实ip

zuul:
  routes:
    user-provider:
      path: /user/**
      serviceId: user-provider